global:
  scrape_interval: 15s # How often to scrape targets by default
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:3002']

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:3003']
